# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185Iw_iVvb2Hpi2HW7X2fyTVU0Bo_JDoH
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import json
import logging

logging.basicConfig(
    filename="scraper.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

logging.info("Web Scraper Started")

url = "https://www.bbc.com/news"

try:
    response = requests.get(url)
    response.raise_for_status()
    print("Website accessed successfully.")
    logging.info("Website accessed successfully.")
except Exception as e:
    print("Error:", e)
    logging.error(str(e))

soup = BeautifulSoup(response.text, "html.parser")

headlines = []

for item in soup.find_all("h2"):
    title = item.get_text(strip=True)

    if title and title not in headlines:
        headlines.append(title)

print("="*60)
print("LATEST BBC NEWS HEADLINES")
print("="*60)

for i, title in enumerate(headlines, 1):
    print(f"{i}. {title}")

df = pd.DataFrame({
    "Headline": headlines
})

df.to_csv("headlines.csv", index=False)

print("CSV file created successfully.")
logging.info("CSV file created.")

with open("headlines.json", "w") as file:
    json.dump(headlines, file, indent=4)

print("JSON file created successfully.")
logging.info("JSON file created.")

from google.colab import files

files.download("headlines.csv")
files.download("headlines.json")