# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12tf5IMu5JDomG7C4euQDwPBl4q7ZCEZ1
"""

!pip install flask pyngrok

from flask import Flask, request, redirect, session, render_template_string
import sqlite3
from werkzeug.security import generate_password_hash, check_password_hash
from pyngrok import ngrok
import threading

app = Flask(__name__)
app.secret_key = "secret123"

def init_db():

    conn = sqlite3.connect("notes.db")

    cur = conn.cursor()

    cur.execute("""
    CREATE TABLE IF NOT EXISTS users(

        id INTEGER PRIMARY KEY AUTOINCREMENT,

        username TEXT UNIQUE,

        password TEXT
    )
    """)

    cur.execute("""
    CREATE TABLE IF NOT EXISTS notes(

        id INTEGER PRIMARY KEY AUTOINCREMENT,

        username TEXT,

        note TEXT
    )
    """)

    conn.commit()

    conn.close()

init_db()

@app.route("/")
def home():

    if "user" in session:
        return redirect("/dashboard")

    return redirect("/login")

@app.route("/register", methods=["GET", "POST"])
def register():

    if request.method == "POST":

        username = request.form["username"]
        password = generate_password_hash(request.form["password"])

        conn = sqlite3.connect("notes.db")
        cur = conn.cursor()

        try:
            cur.execute(
                "INSERT INTO users(username,password) VALUES(?,?)",
                (username, password)
            )

            conn.commit()

            conn.close()

            return redirect("/login")

        except:

            conn.close()

            return "Username already exists!"

    return render_template_string("""

    <html>

    <head>

    <title>Register</title>

    <style>

    body{
        font-family:Arial;
        background:#f2f2f2;
        text-align:center;
        margin-top:80px;
    }

    .box{
        width:350px;
        margin:auto;
        background:white;
        padding:20px;
        border-radius:8px;
    }

    input{
        width:90%;
        padding:10px;
        margin:8px;
    }

    button{
        padding:10px 20px;
        cursor:pointer;
    }

    </style>

    </head>

    <body>

    <div class="box">

    <h2>User Registration</h2>

    <form method="POST">

    <input
        name="username"
        placeholder="Username"
        required>

    <input
        type="password"
        name="password"
        placeholder="Password"
        required>

    <button>Register</button>

    </form>

    <br>

    <a href="/login">Already have an account? Login</a>

    </div>

    </body>

    </html>

    """)

@app.route("/login", methods=["GET","POST"])
def login():

    if request.method=="POST":

        username=request.form["username"]
        password=request.form["password"]

        conn=sqlite3.connect("notes.db")
        cur=conn.cursor()

        cur.execute(
            "SELECT password FROM users WHERE username=?",
            (username,)
        )

        user=cur.fetchone()

        conn.close()

        if user and check_password_hash(user[0],password):

            session["user"]=username

            return redirect("/dashboard")

        else:

            return "Invalid Username or Password"

    return render_template_string("""

    <html>

    <head>

    <title>Login</title>

    <style>

    body{

    font-family:Arial;

    background:#f2f2f2;

    text-align:center;

    margin-top:80px;

    }

    .box{

    width:350px;

    margin:auto;

    background:white;

    padding:20px;

    border-radius:8px;

    }

    input{

    width:90%;

    padding:10px;

    margin:8px;

    }

    button{

    padding:10px 20px;

    }

    </style>

    </head>

    <body>

    <div class="box">

    <h2>User Login</h2>

    <form method="POST">

    <input
    name="username"
    placeholder="Username"
    required>

    <input
    type="password"
    name="password"
    placeholder="Password"
    required>

    <button>Login</button>

    </form>

    <br>

    <a href="/register">Create Account</a>

    </div>

    </body>

    </html>

    """)

@app.route("/dashboard")
def dashboard():

    if "user" not in session:

        return redirect("/login")

    conn=sqlite3.connect("notes.db")

    cur=conn.cursor()

    cur.execute(

        "SELECT id,note FROM notes WHERE username=?",

        (session["user"],)

    )

    notes=cur.fetchall()

    conn.close()

    html="""

    <html>

    <head>

    <title>Dashboard</title>

    <style>

    body{

    font-family:Arial;

    margin:40px;

    background:#f5f5f5;

    }

    textarea{

    width:100%;

    height:100px;

    }

    button{

    padding:10px 20px;

    margin-top:10px;

    }

    .note{

    background:white;

    padding:15px;

    margin:15px 0;

    border-radius:6px;

    }

    a{

    text-decoration:none;

    }

    </style>

    </head>

    <body>

    <h2>Welcome {{user}}</h2>

    <a href="/logout">Logout</a>

    <hr>

    <form action="/add" method="POST">

    <textarea
    name="note"
    placeholder="Write your note..."
    required></textarea>

    <br>

    <button>Add Note</button>

    </form>

    <hr>

    {% for note in notes %}

    <div class="note">

    {{note[1]}}

    <br><br>

    <a href="/delete/{{note[0]}}">

    Delete

    </a>

    </div>

    {% endfor %}

    </body>

    </html>

    """

    return render_template_string(

        html,

        user=session["user"],

        notes=notes

    )

@app.route("/add", methods=["POST"])
def add_note():

    if "user" not in session:
        return redirect("/login")

    note = request.form["note"]

    conn = sqlite3.connect("notes.db")
    cur = conn.cursor()

    cur.execute(
        "INSERT INTO notes(username,note) VALUES(?,?)",
        (session["user"], note)
    )

    conn.commit()
    conn.close()

    return redirect("/dashboard")

@app.route("/delete/<int:id>")
def delete_note(id):

    if "user" not in session:
        return redirect("/login")

    conn = sqlite3.connect("notes.db")
    cur = conn.cursor()

    cur.execute(
        "DELETE FROM notes WHERE id=?",
        (id,)
    )

    conn.commit()
    conn.close()

    return redirect("/dashboard")

@app.route("/logout")
def logout():

    session.pop("user", None)

    return redirect("/login")

ngrok.kill()

def run():
    app.run(port=5000)

thread = threading.Thread(target=run)
thread.start()

def run():
    app.run(port=5000)

thread = threading.Thread(target=run)
thread.start()

"""Note:
This Flask application is intended to be executed in a local Python environment.
Deployment through Google Colab requires an external tunneling service (such as ngrok), which has been omitted from this submission.
"""

